//
//  ImageCollectionInteractor.swift
//  ImageExample_Clean_Swift
//
//  Created by SHIN YOON AH on 9/23/24.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ImageCollectionBusinessLogic
{
  func doSomething(request: ImageCollection.Something.Request)
}

protocol ImageCollectionDataStore
{
  //var name: String { get set }
}

class ImageCollectionInteractor: ImageCollectionBusinessLogic, ImageCollectionDataStore
{
  var presenter: ImageCollectionPresentationLogic?
  var worker: ImageCollectionWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: ImageCollection.Something.Request)
  {
    worker = ImageCollectionWorker()
    worker?.doSomeWork()
    
    let response = ImageCollection.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
