//
//  ImageCollectionWorker.swift
//  ImageExample_Clean_Swift
//
//  Created by SHIN YOON AH on 9/23/24.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class ImageCollectionWorker
{
  func doSomeWork()
  {
  }
}
