//
//  ImageCollectionPresenter.swift
//  ImageExample_Clean_Swift
//
//  Created by SHIN YOON AH on 9/23/24.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ImageCollectionPresentationLogic
{
  func presentSomething(response: ImageCollection.Something.Response)
}

class ImageCollectionPresenter: ImageCollectionPresentationLogic
{
  weak var viewController: ImageCollectionDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: ImageCollection.Something.Response)
  {
    let viewModel = ImageCollection.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
