//
//  ImageCollectionRouter.swift
//  ImageExample_Clean_Swift
//
//  Created by SHIN YOON AH on 9/23/24.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ImageCollectionRoutingLogic
{
  //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol ImageCollectionDataPassing
{
  var dataStore: ImageCollectionDataStore? { get }
}

class ImageCollectionRouter: NSObject, ImageCollectionRoutingLogic, ImageCollectionDataPassing
{
  weak var viewController: ImageCollectionViewController?
  var dataStore: ImageCollectionDataStore?
  
  // MARK: Routing
  
  //func routeToSomewhere(segue: UIStoryboardSegue?)
  //{
  //  if let segue = segue {
  //    let destinationVC = segue.destination as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //  } else {
  //    let storyboard = UIStoryboard(name: "Main", bundle: nil)
  //    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //    navigateToSomewhere(source: viewController!, destination: destinationVC)
  //  }
  //}

  // MARK: Navigation
  
  //func navigateToSomewhere(source: ImageCollectionViewController, destination: SomewhereViewController)
  //{
  //  source.show(destination, sender: nil)
  //}
  
  // MARK: Passing data
  
  //func passDataToSomewhere(source: ImageCollectionDataStore, destination: inout SomewhereDataStore)
  //{
  //  destination.name = source.name
  //}
}
